/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.Ejemplos.internos;

/**
 *
 * @author iNZr
 */
public class ejemplo1 extends javax.swing.JInternalFrame {

    /**
     * Creates new form ejemplo1
     */
    public ejemplo1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("\t\t\t¡¡Al fin!! Nuestro primer proyecto\n**Recuerda que puedes minimizar esta ventana o cerrarla, mientras ves el video de apoyo :D.\nEmpezaremos abriendo NetBeans y crearemos un proyecto nuevo.\n->Archivo/Proyecto Nuevo...\nSe desplegará una opción del lado izquierdo,que contiene el tipo del proyecto, escogeremos\nla categoría \"JAVA\" bien,ahora del lado derecho,vamos a seleccionar la opción...\n\n\"Java Application\", después seleccionamos siguiente.\n\nAhora vamos a establecer el nombre al proyecto de JAVA.\nSi deseamos guardar el proyecto en otra ubicación,buscamos manualmente el lugar.\n\nCrear clase principal(Create Main Class) Si observamos, notarás que por defecto del software,\nnos tildará la opción, esto se debe a que, Netbeans nos apoya en cuanto al código que vamos a ejecutar.\nEn pocas palabras, se refiere a un seguimiento de instrucciones que desde ese código o instrucción.\nSe va a realizar conforme vayamos asignando que lo haga.");
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1369, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
