/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.Ejemplos;

import java.util.Scanner;
import javax.swing.JOptionPane;
import vistas.Ejemplos.ER;

/**
 *
 * @author iNZr
 */
public class EU1 extends javax.swing.JFrame {

    /**
     * Creates new form ER
     */
    public EU1() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("Instituto Tecnológico de Cd. Victoria.");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons/icons8_test_passed_127px_1.png"))); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("\n\nResponde con número 1 para teclear (Sí)\n\ny teclea con el número 2 para responder (No)\n\nCada respuesta tiene un valor de 10 puntos \n\n y no representa nada negativo para ti :)");
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setText("UNIDAD II");

        jButton1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton1.setText("Iniciar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(63, 63, 63)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(173, 173, 173))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(236, 236, 236))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(255, 255, 255))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(65, 65, 65)
                .addComponent(jButton1)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String bienvenida = "Bienvenido!\n"
                + "\n Teclea el número 1 para (Sí)\n"
                + " Teclea el número 2 para (No)\n"
                + "\n Cada respuesta tiene un valor \n"
                + "\n y no representa nada negativo para ti :)";
        int valorPreguntau2 = 20;
        int puntajeu2 = 0;
        
        //Primera pregunta y respuesta
        String primeraP = "\n ¿Cuál es el lenguaje más usado?\n" + ""
                + "\n1.- Java\n"
                + "\n2.- C";
        String primeraR = "1";

        //Segunda pregunta y respuesta
        String segundaP = "\n ¿Cuál sintáxis está correcta?\n"
                + "\n1.- a+b=5\n"
                + "\n2.- a+b=c";
        String segundaR = "2";
        //Tercera pregunta y respuesta
        String terceraP = "\n ¿Java se usa en millones de dispositivos?\n"
                + "\n1.- Si\n"
                + "\n2.- No";
        String terceraR = "1";
        //Cuarta pregunta y respuesta
        String cuartaP = "\n¿Son ejemplos de Enteros?\n"
                + "\n1.- 10, 5 , 1 ,13, 8\n"
                + "\n2.- 10.0, 20.0, 30.0, 40.0, 50.0";
        String cuartaR = "1";
        //quinta pregunta y respuesta
        String quintaP = "Cuáles son ejemplos de Strings?\n"
                + "\n1.- Hola, Crayola, y Mundo\n"
                + "\n2.- 123456, Hola_Mundo, 654321";
        String quintaR = "1";

        //Nuestro Scanner
        Scanner scanner = new Scanner(System.in);
        //Empieza el examen
        JOptionPane.showMessageDialog(null, bienvenida);
        //System.out.println(bienvenida);
        JOptionPane.showMessageDialog(null, "\r Primera pregunta...");
        //System.out.println("Primera pregunta :");
        //primera pregunta
        JOptionPane.showMessageDialog(null, primeraP);
        //JOptionPane.showMessageDialog(null,primeraP);
        //System.out.println(primeraP);
        //JOptionPane.showInputDialog(scanner.nextLine());
        String pR = JOptionPane.showInputDialog("");
        if (pR.equalsIgnoreCase(primeraR)) {
            //JOptionPane.showConfirmDialog(null,"Bien");
            puntajeu2 = puntajeu2 + 1;
        }
        //segunda pregunta
        JOptionPane.showMessageDialog(null, segundaP);
        String sR = JOptionPane.showInputDialog("");
        if (sR.equalsIgnoreCase(segundaR)) {
            puntajeu2 = puntajeu2 + 1;
        }
        //tercera pregunta
        //System.out.println(terceraP);
        JOptionPane.showMessageDialog(null, terceraP);
        String tR = JOptionPane.showInputDialog("");
        if (tR.equalsIgnoreCase(terceraR)) {
            puntajeu2 = puntajeu2 + 1;
        }
        //cuarta pregunta
        //System.out.println(cuartaP);
        JOptionPane.showMessageDialog(null, cuartaP);
        String cR = JOptionPane.showInputDialog("");
        if (cR.equalsIgnoreCase(cuartaR)) {
            puntajeu2 = puntajeu2 + 1;
        }
        //quinta pregunta
        //System.out.println(quintaP);
        JOptionPane.showMessageDialog(null, quintaP);
        String qR = JOptionPane.showInputDialog("");
        if (qR.equalsIgnoreCase(quintaR)) {
            puntajeu2 = puntajeu2 + 1;
        }
        //mensaje final y puntuación
        JOptionPane.showMessageDialog(null, "\nEl test ha finalizado");
        JOptionPane.showMessageDialog(null, "\nSu puntuación fue: " + valorPreguntau2 * puntajeu2);
       
        //System.out.println(valorPregunta*puntaje);
    
        
         
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EU1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EU1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EU1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EU1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            new EU1().setVisible(true);
               
                
                                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
